name: easy_worker
description: A package to make isolate usage as easy as possible.
version: 1.2.3
homepage: https://github.com/raj457036/simple_worker
repository: https://github.com/raj457036/simple_worker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: