name: easy_worker
description: A package to make isolate usage as easy as possible.
version: 1.0.0
homepage: https://github.com/raj457036/simple_worker
repository: https://github.com/raj457036/simple_worker

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: